version: "3.9"
services:
  airflow-webserver:
    build: .
    container_name: airflow-webserver
    restart: always
    ports:
      - "8080:8080"
    command: webserver
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./airflow_db:/opt/airflow/airflow_home
      - ./scripts:/opt/airflow/scripts

  airflow-scheduler:
    build: .
    container_name: airflow-scheduler
    restart: always
    command: scheduler
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./airflow_db:/opt/airflow/airflow_home
      - ./scripts:/opt/airflow/scripts
